name = "billing"
main = "src/index.ts"
account_id = "5c5263e05bb1e54242b1afb12a5c9259"

routes = [
  { pattern = "console.mytiki.com/api/latest/billing", zone_id = "7be31970110fa56b1f8e1fe915a8b938" },
  { pattern = "console.mytiki.com/api/latest/billing/*", zone_id = "7be31970110fa56b1f8e1fe915a8b938" },
]

compatibility_date = "2023-02-02"

[vars]
ORIGIN = "https://console.mytiki.com"
BILLING_PAGE = "billing"
L0_AUTH_DOMAIN = "https://auth.l0.mytiki.com"

STRIPE_IGT_PRICE_ID = "price_1NBX9lDveWor0wgFd9dFH8Sl"
STRIPE_IGT_PRODUCT_ID = "prod_NxPayH6ltybQVV"

STRIPE_LMSM_PRICE_ID = "price_1NBV5fDveWor0wgFKjcWHC5N"
STRIPE_LMSM_PRODUCT_ID = "prod_NxPvzVRz2wXzPx"

STRIPE_LMSMAO_PRICE_ID = "price_1NBXCxDveWor0wgFa71FZFkn"
STRIPE_LMSMAO_PRODUCT_ID = "prod_NxPxbsvCIhGm0I"

# The necessary secrets are:
# - STRIPE_SK
