name = "billing"
main = "src/index.ts"
account_id = "5c5263e05bb1e54242b1afb12a5c9259"

routes = [
  { pattern = "console.mytiki.com/api/latest/billing", zone_id = "7be31970110fa56b1f8e1fe915a8b938" },
  { pattern = "console.mytiki.com/api/latest/billing/subscriptions", zone_id = "7be31970110fa56b1f8e1fe915a8b938" },
  { pattern = "console.mytiki.com/api/latest/billing/checkout", zone_id = "7be31970110fa56b1f8e1fe915a8b938" }
]

compatibility_date = "2023-02-02"

[vars]
ORIGIN = "https://console.mytiki.com"
BILLING_PAGE = "billing"
L0_AUTH_DOMAIN = "https://auth.l0.mytiki.com"

STRIPE_IGT_PRICE_ID = ""
STRIPE_IGT_PRODUCT_ID = ""

STRIPE_LMSM_PRICE_ID = ""
STRIPE_LMSM_PRODUCT_ID = ""

STRIPE_LMSMAO_PRICE_ID = ""
STRIPE_LMSMAO_PRODUCT_ID = ""

# The necessary secrets are:
# - STRIPE_SK
